# Generated by Django 4.1.1 on 2022-09-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('short_details', models.TextField(blank=True, null=True)),
                ('image', models.FileField(default='default.png', upload_to='menu/menu-images')),
                ('available_time', models.CharField(choices=[('lunch', 'Lunch 1pm - 4pm'), ('Dinner', 'Dinner 6pm - 11pm')], max_length=30)),
                ('ability_today', models.CharField(choices=[('yes', 'Yes'), ('out-of-stock', 'Out Of Stock')], default='yes', max_length=30)),
            ],
        ),
    ]
