# Generated by Django 4.1.1 on 2022-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_price_menu_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.FileField(default='menu/menu-images/default.png', upload_to='menu/menu-images'),
        ),
    ]
