# Generated by Django 4.1.1 on 2022-09-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='short_details',
            field=models.TextField(),
        ),
    ]
