# Generated by Django 4.1.1 on 2022-10-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menu_price_alter_menu_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='available_time',
            field=models.CharField(choices=[('lunch', 'Lunch 1pm - 4pm'), ('dinner', 'Dinner 6pm - 11pm')], max_length=30),
        ),
    ]
