# Generated by Django 4.1.1 on 2022-10-09 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(default=order.models.random_string, editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('set_menu_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('order_in_queue', 'Order in queue'), ('order_accepted', 'Order accepted'), ('order_processing', 'Order processing'), ('order_delivered', 'Order delivered')], default='order_in_queue', max_length=30)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
