# Generated by Django 4.1.1 on 2022-10-13 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_rename_order_id_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order_in_queue', 'Order in queue'), ('order_accepted', 'Order accepted'), ('order_processing', 'Order processing'), ('order_delivered', 'Order delivered')], default='order_in_queue', max_length=50),
        ),
    ]
